# Generated by Django 3.2.15 on 2022-11-20 15:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=True, populate_from='user'),
            preserve_default=False,
        ),
    ]
