# Generated by Django 3.2.15 on 2022-12-09 20:53

from django.db import migrations, models
import utils.size_validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221203_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-user.png', upload_to='profile_pics', validators=[utils.size_validator.validate_max_size]),
        ),
    ]
