# Generated by Django 3.2.15 on 2022-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artwork',
            field=models.ImageField(default='default-artwork.jpg', upload_to='artworks'),
        ),
    ]
