# Generated by Django 3.2.15 on 2022-12-09 12:47

from django.db import migrations, models
import utils.size_validator


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artwork',
            field=models.ImageField(default='default-artwork.png', upload_to='artworks', validators=[utils.size_validator.validate_max_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=600),
        ),
    ]
